### ISSUE TITLE
"hugo --source=. --destination=export" encounter error

### ISSUE THREAD

**Issue by luckypoem** [Fale/fale.io#1]
hi.

root@localhost:/usr/local/hugo-site/examples/fale.io# hugo --source=. --destination=export
Started building sites ...
ERROR 2017/04/17 15:38:16 Error while rendering "page": template: publication/single.html:1:3: executing "publication/single.html" at <partial "header.html...>: error calling partial: Partial "header.html" not found
root@localhost:/usr/local/hugo-site/examples/fale.io# 

root@localhost:/usr/local/hugo-site/examples/fale.io# ls
archetypes   content  export   LICENSE    static  update_website.sh
config.yaml  data     layouts  README.md  themes
root@localhost:/usr/local/hugo-site/examples/fale.io# find . -name single.html
./layouts/publication/single.html
root@localhost:/usr/local/hugo-site/examples/fale.io# find . -name header.html
root@localhost:/usr/local/hugo-site/examples/fale.io# nano layouts/publication/single.html
root@localhost:/usr/local/hugo-site/examples/fale.io# find . -name sidebar.html
root@localhost:/usr/local/hugo-site/examples/fale.io# find . -name footer.html
root@localhost:/usr/local/hugo-site/examples/fale.io#

how to fix it?

**Comment by Fale** [comment]
I think you have not checked out the theme, which is in a git submodule.

So:

    git submodule init
    git submodule update
